### PR TITLE
Add default value for typed_field_mapper

### PR DESCRIPTION
**Pull request by PowerKiKi**
I forgot to set a default value in my previous PR, which may have caused warnings.

### CODE REVIEW

**Review by Slamdunk — APPROVED** [review]

**Comment by snapshotpl** [comment]
After this release I still get a warnings:
```
Warning: Undefined array key "typed_field_mapper" in /var/www/vendor/roave/psr-container-doctrine/src/ConfigurationFactory.php on line 91
Warning: Undefined array key "typed_field_mapper" in /var/www/vendor/roave/psr-container-doctrine/src/ConfigurationFactory.php on line 93

```

**Comment by PowerKiKi** [comment]
Cannot reproduce here. Are you triple sure that you are on 5.3**.1** ? do you have a reproduction case ?

_PS: I actually could reproduce, so #135_

**Comment by Slamdunk** [comment]
@snapshotpl it should be fixed in https://github.com/Roave/psr-container-doctrine/releases/tag/5.2.2

**Comment by snapshotpl** [comment]
:heavy_check_mark: confirm

**Pull request merged**
