### PR TITLE
Allow `psr/container:^2`

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by Ocramius** [comment]
@snapshotpl your **PUBLIC**  key `018185A24DB71DCD` is not present on github BTW :)

**Review by Ocramius — CHANGES_REQUESTED** [review]
Note: we're only testing `locked` dependencies here.

Can we somehow generate a `composer.lock` with `psr/container:^2`?

**Comment by Ocramius** [comment]
Uh-oh, can of worms opened? :|

**Comment by snapshotpl** [comment]
One of worm looks like brother of https://github.com/doctrine/DoctrineORMModule/pull/708

**Comment by snapshotpl** [comment]
Not sure what to to with last one. Probably [this](https://github.com/doctrine/dbal/pull/5077) caused this issue. @greg0ire can you help?

**Comment by greg0ire** [comment]
Here is the failing test:

https://github.com/Roave/psr-container-doctrine/blob/653bdbacf92ef563cd82904595b112b692067cc6/test/ConnectionFactoryTest.php#L151-L161

The DBAL used to have 2 ways of making a type commented, and I believe there should be only one, which should be implementing `requiresSQLCommentHint()`. I'd remove that assertion and deprecate `doctrine_commented_types`, I don't think it makes sense to use it.

**Comment by greg0ire** [comment]
Also, I think the PR causing the issue you are experiencing is actually this one: https://github.com/doctrine/dbal/pull/5058

**Comment by snapshotpl** [comment]
Thanks @greg0ire !

**Comment by Ocramius** [comment]
@snapshotpl before I merge, can you add your public `018185A24DB71DCD` GPG key to github? Go to https://github.com/settings/gpg/new and set it there :)

**Comment by snapshotpl** [comment]
done!

**Comment by Ocramius** [comment]
Awesome, thanks!

**Review by Ocramius — APPROVED** [review]
Looking good! Thanks for the CI overhaul and work around the support of newer DBAL versions!

**Pull request merged**
