### PR TITLE
Remove obscure `__callStatic` behaviors, prefer natural constructors

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by bcremer** [comment]
Wasn't that a feature so that named entity managers can be easlily registered in a laminas container via configuration like so?

```php
<?php
return [
    'doctrine.SECTION.orm_other' => [EntityManagerFactory::class::class, 'orm_other'],
];
```

Recent versions of the laminas support closures in the cached config so it can be rewritten as as the following: 


```php
<?php
return [
    'doctrine.SECTION.orm_other' => fn() => new EntityManagerFactory('orm_other'),
];
```

**Comment by Slamdunk** [comment]
Indeed. Is this a blocker in your opinion?

**Comment by bcremer** [comment]
Not a blocker, just a general observation. Support for closures in cached configs is supported for a long time now and the "new" syntax should be easy enough for most people.

**Comment by bcremer** [comment]
But the calls should be changed in the examples in the README https://github.com/Roave/psr-container-doctrine?tab=readme-ov-file#configuration

https://github.com/Roave/psr-container-doctrine/pull/123/files

**Pull request merged**
